Vagrant.configure("2") do |config|
    # Gemeinsame Basis-Konfiguration
    config.vm.box = "ubuntu/bionic64"
   
   # Netzwerkpakete für mDNS
    config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y avahi-daemon libnss-mdns openssh-server rsync git
     systemctl restart avahi-daemon
    SHELL
   
    # Allow Password-Login with SSH
    config.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
     systemctl restart sshd.service
    SHELL
   
    # Maschine 1 (vm01)
    config.vm.define "vm-web" do |vmweb|
     vmweb.vm.hostname = "vm-web"
     vmweb.vm.network "private_network", ip: "192.168.60.10"
     vmweb.vm.network "forwarded_port", guest: 80, host: 8080
   
    # Maschine 1 apache
    vmweb.vm.provision "shell", inline: <<-SHELL
     apt update
     apt-get install apache2 -y
     cd /home/vagrant
     git clone https://github.com/lazinn/vagrant.git
     sleep 20
     cd vagrant/Dateien/web_db
     rm /var/www/html/index.html
     mv /home/vagrant/vagrant/Dateien/web_db/index.html /var/www/html/
     chown www-data:www-data /var/www/html/index.php
    SHELL
    end
   
    # Maschine 2 (vm-db)
    config.vm.define "vm-db" do |vmdb|
     vmdb.vm.hostname = "vm-db"
     vmdb.vm.network "private_network", ip: "192.168.60.20"
    
   #install mariadb
    vmdb.vm.provision "shell", inline: <<-SHELL
     apt update
     apt-get install mariadb-server -y
    SHELL
    end
   end