Vagrant.configure("2") do |config|
    # Gemeinsame Basis-Konfiguration
    config.vm.box = "ubuntu/bionic64"
   
    # Netzwerkpakete für mDNS
    config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y avahi-daemon libnss-mdns openssh-server rsync
     apt-get install -y git
     systemctl restart avahi-daemon
    SHELL
   
    # Allow Password-Login with SSH
    config.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
     systemctl restart sshd.service
    SHELL
   
    # Maschine 1 (vm01)
    config.vm.define "vm-dockge" do |vmdockge|
     vmdockge.vm.hostname = "vm-dockge"
     vmdockge.vm.network "private_network", ip: "192.168.60.10"
     vmdockge.vm.network "forwarded_port", guest: 80, host: 90
    
     # Maschine 1 install docker
     vmdockge.vm.provision "shell", inline: <<-SHELL
     # Add Docker's official GPG key:
       apt update
       apt install -y apt-transport-https ca-certificates curl software-properties-common
       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
       add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
       apt install -y docker-ce
       curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
       systemctl enable docker
       systemctl start docker
       usermod -aG docker vagrant
       newgrp docker
       mkdir -p /opt/stacks /opt/dockge
       cd /opt/dockge
       curl https://raw.githubusercontent.com/louislam/dockge/master/compose.yaml --output compose.yaml
       docker compose up -d
     SHELL
    end


end




