Vagrant.configure("2") do |config|
    # Gemeinsame Basis-Konfiguration
    config.vm.box = "ubuntu/bionic64"
   
    # Netzwerkpakete für mDNS
    config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y avahi-daemon libnss-mdns openssh-server rsync
     apt-get install -y git
     systemctl restart avahi-daemon
    SHELL
   
    # Allow Password-Login with SSH
    config.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
     systemctl restart sshd.service
    SHELL
   
    # Maschine 1 (vm01)
    config.vm.define "vm-dockge" do |vmdockge|
     vmdockge.vm.hostname = "vm-dockge"
     vmdockge.vm.network "private_network", ip: "192.168.60.10"
     vmdockge.vm.network "forwarded_port", guest: 80, host: 90
    
     # Maschine 1 apache
     vmdockge.vm.provision "shell", inline: <<-SHELL
     # Add Docker's official GPG key:
       apt-get update
       apt-get install ca-certificates curl
       install -m 0755 -d /etc/apt/keyrings
       curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
       chmod a+r /etc/apt/keyrings/docker.as
      
       # Add the repository to Apt sources:
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update
      sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
     SHELL
    end
end




